  version: "3.9"

  services:
    node:
      image: node:24-alpine  
      working_dir: /app
      volumes:
        - .:/app
        - node_modules:/app/node_modules
      #command: sh -c "npm install && npm run dev;" 目前沒用
      command: sh -c "npm install && npx nodemon --legacy-watch src/server.js"
      #command: sh -c "npm install && npm start"
      environment:
        PORT: 3000
        PGHOST: db
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: ${POSTGRES_PASSWORD}
        PGDATABASE: postgres
        # 如果你用 DATABASE_URL，也可加：
        # DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/app
      ports:
        - "3000:3000"
      depends_on:
        postgres:
          condition: service_healthy
    
    postgres:
      image: postgres:16
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: postgres
      volumes:
        - pgdata:/var/lib/postgresql/data
      # 若你不需要從主機連線，可拿掉下面 ports
      ports:
        - "5432:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
        interval: 5s
        timeout: 3s
        retries: 10

    cloudbeaver:
      image: dbeaver/cloudbeaver:latest
      ports:
        - "8978:8978"
      volumes:
        - cloudbeaver_data:/opt/cloudbeaver/workspace
      depends_on:
        - postgres

  volumes:
    pgdata:
    node_modules:
    cloudbeaver_data:

